apiVersion: v1
kind: Service
metadata:
  name: rent-car-database
  labels:
    app: rent-car
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: rent-car
    tier: database